/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.rx50.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {
  TextPlayer player1;
  TextPlayer player2;

  public App(TextPlayer player1, TextPlayer player2) {
    this.player1 = player1;
    this.player2 = player2;
  }

  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException {
    while (true) {
      player1.playOneTurn(player2.theBoard, player2.view, player2.name);
      if (player2.checkLost()) {
        System.out.println(player1.name + " has won! " + player2.name + " has lost!");
        break;
      }
      player2.playOneTurn(player1.theBoard, player1.view, player1.name);
      if (player1.checkLost()) {
        System.out.println(player2.name + " has won! " + player1.name + " has lost!");
        break;
      }
    }
  }

  public static void main(String[] args) throws IOException {
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));

    V2ShipFactory factory = new V2ShipFactory();
    TextPlayer player1 = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer player2 = new TextPlayer("B", b2, input, System.out, factory);

    App App = new App(player1, player2);
    App.doPlacementPhase();
    App.doAttackingPhase();
  }
}
