/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.rx50.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  final Board<Character> theBoard;
  final BoardTextView view;
  final BufferedReader inputReader;
  final PrintStream out;

  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
  }

  /**
   * read placement and deal with it
   */
  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  public void doOnePlacement() throws IOException {
    // read a Placement (prompt: "Where would you like to put your ship?")
    Placement p = readPlacement("Where would you like to put your ship?");
    // Create a basic ship based on the location in that Placement
    RectangleShip<Character> b = new RectangleShip<Character>(p.getWhere(), 's', '*');
    // Add that ship to the board
    theBoard.tryAddShip(b);
    // Print out the board (to out, not to System.out)
    out.println(view.displayMyOwnBoard());
  }

  public static void main(String[] args) throws IOException {
    Board myBoard = new BattleShipBoard<Character>(10, 20);
    App myApp = new App(myBoard, new InputStreamReader(System.in), System.out);
    myApp.doOnePlacement();
  }
}
